spring:
  profiles: production
  application:
    name: omar-oauth-service
  cloud:
    config:
      enabled: true
      uri: ${SPRING_CONFIG_URI:http://omar-config-server:8888/omar-config-server}
    discovery:
      enabled: true